backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/PortfolioController.java
backend/src/main/java/org/dgu/backend/dto/PortfolioDto.java
backend/src/main/java/org/dgu/backend/repository/PerformanceResultRepository.java
backend/src/main/java/org/dgu/backend/repository/PortfolioOptionRepository.java
backend/src/main/java/org/dgu/backend/repository/PortfolioRepository.java
backend/src/main/java/org/dgu/backend/repository/TradingResultRepository.java
backend/src/main/java/org/dgu/backend/service/PortfolioService.java
backend/src/main/java/org/dgu/backend/service/PortfolioServiceImpl.java

[feat] : 포트폴리오 전체 & 상세 조회 API 구현 (GET)

---

backend/src/main/java/org/dgu/backend/common/BaseEntity.java
backend/src/main/java/org/dgu/backend/domain/Portfolio.java
backend/src/main/java/org/dgu/backend/domain/PortfolioOption.java
backend/src/main/java/org/dgu/backend/domain/TradingResult.java
backend/src/main/java/org/dgu/backend/domain/User.java
backend/src/main/resources/application.yml
backend/src/main/resources/data.sql

[feat] : BaseEntity & 테스트 유저 추가

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/PortfolioController.java
backend/src/main/java/org/dgu/backend/exception/GlobalExceptionHandler.java
backend/src/main/java/org/dgu/backend/repository/PortfolioRepository.java
backend/src/main/java/org/dgu/backend/service/AuthServiceImpl.java
backend/src/main/java/org/dgu/backend/service/BackTestingServiceImpl.java
backend/src/main/java/org/dgu/backend/service/CandleInfoServiceImpl.java
backend/src/main/java/org/dgu/backend/service/MarketServiceImpl.java
backend/src/main/java/org/dgu/backend/service/PortfolioService.java
backend/src/main/java/org/dgu/backend/service/PortfolioServiceImpl.java
backend/src/main/java/org/dgu/backend/util/JwtUtil.java

[feat] : 포트폴리오 삭제 API 구현

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/PortfolioController.java
backend/src/main/java/org/dgu/backend/domain/PerformanceResult.java
backend/src/main/java/org/dgu/backend/domain/Portfolio.java
backend/src/main/java/org/dgu/backend/dto/PortfolioDto.java
backend/src/main/java/org/dgu/backend/service/PortfolioService.java
backend/src/main/java/org/dgu/backend/service/PortfolioServiceImpl.java

[feat] : 포트폴리오 정보 수정 API 구현 (PATCH)

---

backend/src/main/java/org/dgu/backend/dto/BackTestingDto.java
backend/src/main/java/org/dgu/backend/exception/BackTestingErrorResult.java
backend/src/main/java/org/dgu/backend/exception/BackTestingException.java
backend/src/main/java/org/dgu/backend/exception/GlobalExceptionHandler.java
backend/src/main/java/org/dgu/backend/exception/NumberErrorResult.java
backend/src/main/java/org/dgu/backend/exception/NumberException.java
backend/src/main/java/org/dgu/backend/service/BackTestingCalculator.java
backend/src/main/java/org/dgu/backend/service/BackTestingServiceImpl.java
backend/src/main/java/org/dgu/backend/util/NumberUtil.java

[refactor] : 손절 & 익절 계산 방식 리팩토링

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/PortfolioController.java
backend/src/main/java/org/dgu/backend/domain/Portfolio.java
backend/src/main/java/org/dgu/backend/dto/PortfolioDto.java
backend/src/main/java/org/dgu/backend/service/PortfolioService.java
backend/src/main/java/org/dgu/backend/service/PortfolioServiceImpl.java

---
- 포트폴리오 즐겨찾기 추가 API 구현
- 포트폴리오 즐겨찾기 삭제 API 구현
---
#21 
---

[feat] : 포트폴리오 즐겨찾기 추가 & 삭제 API 구현 

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/BackTestingController.java
backend/src/main/java/org/dgu/backend/domain/Portfolio.java
backend/src/main/java/org/dgu/backend/domain/TradingLog.java
backend/src/main/java/org/dgu/backend/dto/BackTestingDto.java
backend/src/main/java/org/dgu/backend/repository/PortfolioRepository.java
backend/src/main/java/org/dgu/backend/repository/TradingLogRepository.java
backend/src/main/java/org/dgu/backend/service/BackTestingService.java
backend/src/main/java/org/dgu/backend/service/BackTestingServiceImpl.java

[feat] : 최근 백테스팅 결과 조회 API 구현 (GET)

---

backend/src/main/java/org/dgu/backend/dto/BackTestingDto.java
backend/src/main/java/org/dgu/backend/dto/PortfolioDto.java

[refactor] : 일부 API 응답 값 추가

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/UserController.java
backend/src/main/java/org/dgu/backend/domain/UpbitKey.java
backend/src/main/java/org/dgu/backend/dto/UserDto.java
backend/src/main/java/org/dgu/backend/exception/EncryptionErrorResult.java
backend/src/main/java/org/dgu/backend/exception/EncryptionException.java
backend/src/main/java/org/dgu/backend/exception/GlobalExceptionHandler.java
backend/src/main/java/org/dgu/backend/service/UserService.java
backend/src/main/java/org/dgu/backend/service/UserServiceImpl.java
backend/src/main/java/org/dgu/backend/util/AESUtil.java
backend/src/main/java/org/dgu/backend/util/EncryptionUtil.java
backend/src/main/resources/application.yml

[feat] : 유저 업비트 키 등록 API 구현 (POST)

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/UserController.java
backend/src/main/java/org/dgu/backend/domain/User.java
backend/src/main/java/org/dgu/backend/exception/UserErrorResult.java
backend/src/main/java/org/dgu/backend/service/UserService.java
backend/src/main/java/org/dgu/backend/service/UserServiceImpl.java
backend/src/main/resources/data.sql

[feat] : 서비스 약관 동의 여부 등록 API 구현 (POST)

---

backend/src/main/java/org/dgu/backend/auth/info/GoogleUserInfo.java
backend/src/main/java/org/dgu/backend/auth/info/KakaoUserInfo.java
backend/src/main/java/org/dgu/backend/auth/info/NaverUserInfo.java
backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/constant/Coin.java
backend/src/main/java/org/dgu/backend/constant/Provider.java
backend/src/main/java/org/dgu/backend/controller/CandleInfoController.java
backend/src/main/java/org/dgu/backend/controller/ChartController.java
backend/src/main/java/org/dgu/backend/domain/Candle.java
backend/src/main/java/org/dgu/backend/domain/Market.java
backend/src/main/java/org/dgu/backend/dto/ChartDto.java
backend/src/main/java/org/dgu/backend/dto/UpbitDto.java
backend/src/main/java/org/dgu/backend/exception/BackTestingErrorResult.java
backend/src/main/java/org/dgu/backend/exception/ChartErrorResult.java
backend/src/main/java/org/dgu/backend/exception/ChartException.java
backend/src/main/java/org/dgu/backend/exception/GlobalExceptionHandler.java
backend/src/main/java/org/dgu/backend/exception/UpbitErrorResult.java
backend/src/main/java/org/dgu/backend/repository/CandleInfoRepository.java
backend/src/main/java/org/dgu/backend/repository/CandleRepository.java
backend/src/main/java/org/dgu/backend/service/BackTestingServiceImpl.java
backend/src/main/java/org/dgu/backend/service/CandleInfoServiceImpl.java
backend/src/main/java/org/dgu/backend/service/ChartService.java
backend/src/main/java/org/dgu/backend/service/ChartServiceImpl.java
backend/src/main/java/org/dgu/backend/service/DashBoardServiceImpl.java
backend/src/main/java/org/dgu/backend/service/MarketServiceImpl.java
backend/src/main/java/org/dgu/backend/util/CandleDataCollector.java

[feat] : OHLCV 차트 조회 API 구현 (GET)

---

backend/src/main/java/org/dgu/backend/controller/CandleInfoController.java
backend/src/main/java/org/dgu/backend/repository/CandleInfoRepository.java
backend/src/main/java/org/dgu/backend/service/BackTestingCalculator.java
backend/src/main/java/org/dgu/backend/service/BackTestingServiceImpl.java
backend/src/main/java/org/dgu/backend/service/CandleInfoService.java
backend/src/main/java/org/dgu/backend/service/CandleInfoServiceImpl.java
backend/src/main/java/org/dgu/backend/service/CandleInfoUpdater.java
backend/src/main/java/org/dgu/backend/service/ChartServiceImpl.java
backend/src/main/java/org/dgu/backend/util/CandleDataCollector.java
backend/src/main/java/org/dgu/backend/util/CandleUtil.java

[feat] : 차트 관련 요청 시, 최신화 후 반환하는 기능 추가

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/ChartController.java
backend/src/main/java/org/dgu/backend/dto/ChartDto.java
backend/src/main/java/org/dgu/backend/exception/CandleErrorResult.java
backend/src/main/java/org/dgu/backend/exception/CandleException.java
backend/src/main/java/org/dgu/backend/exception/GlobalExceptionHandler.java
backend/src/main/java/org/dgu/backend/exception/MarketErrorResult.java
backend/src/main/java/org/dgu/backend/exception/MarketException.java
backend/src/main/java/org/dgu/backend/service/ChartService.java
backend/src/main/java/org/dgu/backend/service/ChartServiceImpl.java

[feat] : 차트 선택 지표 목록 조회 API 구현 (GET)

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/DashBoardController.java

[feat] : 비트코인 일봉 차트 조회 API 구현 (GET)

---

backend/src/main/java/org/dgu/backend/exception/EncryptionErrorResult.java
backend/src/main/java/org/dgu/backend/exception/UpbitErrorResult.java
backend/src/main/java/org/dgu/backend/service/DashBoardServiceImpl.java
backend/src/main/java/org/dgu/backend/service/UserServiceImpl.java
backend/src/main/java/org/dgu/backend/util/EncryptionUtil.java
backend/src/main/java/org/dgu/backend/util/JwtUtil.java

[refactor] : 업비트 키 복호화 후 요청 & 401 에러 처리 추가

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/TradingController.java
backend/src/main/java/org/dgu/backend/domain/Portfolio.java
backend/src/main/java/org/dgu/backend/domain/TradingOption.java
backend/src/main/java/org/dgu/backend/domain/User.java
backend/src/main/java/org/dgu/backend/dto/PortfolioDto.java
backend/src/main/java/org/dgu/backend/dto/TradingDto.java
backend/src/main/java/org/dgu/backend/exception/GlobalExceptionHandler.java
backend/src/main/java/org/dgu/backend/exception/PortfolioErrorResult.java
backend/src/main/java/org/dgu/backend/exception/TradingErrorResult.java
backend/src/main/java/org/dgu/backend/exception/TradingException.java
backend/src/main/java/org/dgu/backend/repository/PortfolioOptionRepository.java
backend/src/main/java/org/dgu/backend/repository/TradingOptionRepository.java
backend/src/main/java/org/dgu/backend/service/PortfolioServiceImpl.java
backend/src/main/java/org/dgu/backend/service/TradingService.java
backend/src/main/java/org/dgu/backend/service/TradingServiceImpl.java

[feat] : 자동매매 등록 API 구현 (POST)

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/TradingController.java
backend/src/main/java/org/dgu/backend/exception/TradingErrorResult.java
backend/src/main/java/org/dgu/backend/service/TradingService.java
backend/src/main/java/org/dgu/backend/service/TradingServiceImpl.java

[feat] : 자동매매 삭제 API 구현 (DELETE)

---

backend/src/main/java/org/dgu/backend/domain/UserCoin.java
backend/src/main/java/org/dgu/backend/dto/DashBoardDto.java
backend/src/main/java/org/dgu/backend/dto/UpbitDto.java
backend/src/main/java/org/dgu/backend/service/CandleInfoServiceImpl.java
backend/src/main/java/org/dgu/backend/service/CandleInfoUpdater.java
backend/src/main/java/org/dgu/backend/service/DashBoardServiceImpl.java
backend/src/main/java/org/dgu/backend/service/MarketServiceImpl.java
backend/src/main/java/org/dgu/backend/util/CandleUtil.java
backend/src/main/resources/application.yml

[refactor] : 현재가 기준으로 계산하도록 리팩토링

---

backend/src/main/java/org/dgu/backend/common/BaseEntity.java
backend/src/main/java/org/dgu/backend/domain/TradingOption.java
backend/src/main/java/org/dgu/backend/domain/User.java
backend/src/main/java/org/dgu/backend/domain/UserTradingLog.java
backend/src/main/java/org/dgu/backend/dto/TradingDto.java
backend/src/main/java/org/dgu/backend/dto/UpbitDto.java
backend/src/main/java/org/dgu/backend/exception/UpbitErrorResult.java
backend/src/main/java/org/dgu/backend/repository/UserTradingLogRepository.java
backend/src/main/java/org/dgu/backend/service/DashBoardServiceImpl.java
backend/src/main/java/org/dgu/backend/service/OrderService.java
backend/src/main/java/org/dgu/backend/service/OrderServiceImpl.java
backend/src/main/java/org/dgu/backend/service/TradingService.java
backend/src/main/java/org/dgu/backend/service/TradingServiceImpl.java
backend/src/main/java/org/dgu/backend/service/UpbitApiClient.java
backend/src/main/java/org/dgu/backend/service/UpbitAutoTrader.java
backend/src/main/java/org/dgu/backend/util/HashUtil.java

[feat] : 자동매매 기능 구현

---

backend/src/main/java/org/dgu/backend/common/constant/SuccessStatus.java
backend/src/main/java/org/dgu/backend/controller/TradingController.java
backend/src/main/java/org/dgu/backend/dto/TradingDto.java
backend/src/main/java/org/dgu/backend/repository/UserTradingLogRepository.java
backend/src/main/java/org/dgu/backend/service/TradingService.java
backend/src/main/java/org/dgu/backend/service/TradingServiceImpl.java

[feat] : 자동매매 거래 로그 조회 API 구현 (GET)

---

AI/text

- [ O  ] 파일 혹은 폴더명 수정
---
폴더 추가함
---
ex)
- Fixes : #00 (수정중인 이슈)
- Resolves : #100 (무슨 이슈를 해결했는지)
- Ref : #00 #01 (참고할 이슈)
- Related to : #00 #01 (해당 커밋과 관려)
---

Create AI folder

---

AI/introduction.md

-  문서 수정
---
AI 폴더 만듦
-> 실험설계가  끝나 앞으로 실험결과 차곡차곡 올릴 예정!
---
이슈 관련사항 없음
---

[docs] : ai_폴더_생성
